### ISSUE TITLE
Migration to Arbitrum Sepolia (instead of Arbitrum Goerli)

### ISSUE THREAD

**Issue by jaybuidl** [kleros/kleros-v2#1238]
Arbitrum Goerli will be deprecated on November 18 -> no more RPCs available then.

> chain ID: 421614 
> rpc: [https://sepolia-rollup.arbitrum.io/rpcblock](https://t.co/Fe0mQH3JGj) 
> explorer: [https://sepolia-explorer.arbitrum.io](https://t.co/22KyTWtwAK)
> faucet: [https://faucet.quicknode.com/arbitrum/sepolia](https://t.co/h7e3RfUzKf)

[source](https://twitter.com/ArbitrumDevs/status/1703823773571440949)

## Prerequisites
- [ ] Vea between Arbitrum Sepolia and Gnosis testnet
- [x] A randomizer RNG, [deployment addresses](https://randomizer.ai/docs#addresses)
  -  Finally... on December 10 [it was announced on Discord](https://discord.com/channels/1008764401391771650/1008766180598759534/1183413134933901443), the docs and dashboard app are not yet updated as of Dec 15 -> https://sepolia.arbiscan.io/address/0xE775D7fde1d0D09ae627C0131040012ccBcC4b9b
- [x] A subgraph service is available, [Graph supported networks](https://thegraph.com/docs/en/developing/supported-networks/), [Goldsky supported networks](https://docs.goldsky.com/supported-chains)
  - Subgraph PR: https://github.com/graphprotocol/contracts/pull/867
- [x] The wagmi/viem chain is known -> https://github.com/wagmi-dev/viem/pull/1278

## Nice to have
- Explorer: no Etherscan yet, only [Blockscout](https://sepolia-explorer.arbitrum.io/)

**Comment by jaybuidl** [comment]
Vea requires other code changes (Hashi integration) beside migrating to Arbitrum Sepolia. 
In order to avoid delaying the v2 migration, we are proceeding without the crosschain components right now and will add them back later.
