### ISSUE TITLE
Dev tool: dispute preview page improvements

### ISSUE THREAD

**Issue by jaybuidl** [kleros/kleros-v2#1475]
Follow-up on #1103 

```[tasklist]
### Tasks
- [ ] Prettify template and mapping automatically
- [ ] Syntax coloring (JSON)
- [ ] Add a button to fetch a dispute template and mapping from the disputeTemplateID input variable
- [ ] Add a button to fetch the DisputeRequest parameters from a real transaction hash
- [ ] Add bookmarks/shortcuts to existing configs to fetch quickly
```
