### ISSUE TITLE
Compatibility with v1

### ISSUE THREAD

**Issue by jaybuidl** [kleros/kleros-v2#246]
- [ ] KlerosLiquid Wrapper on Ethereum, forwards dispute and appeal requests to v2
- [ ] KlerosLiquid on Gnosis Chain upgrade
- [ ] Bot for KlerosLiquid on Ethereum
- [ ] Bot for KlerosLiquid on Gnosis Chain 
- [ ] Add support for KlerosLiquid Ethereum and Gnosis Chain in the v2 front-end
