### ISSUE TITLE
September Demo

### ISSUE THREAD

**Issue by jaybuidl** [kleros/kleros-v2#253]
## Goal 
1. To demonstrate the functioning of the v2 court for the resolution of a dispute originating from a new Tag Registry on Arbitrum, and the associated cost savings.
1. To demonstrate the new user experience offered by the new front-end.

## Scenario
- John, Joe and Jimmy stake some PNK, hoping to be drawn as jurors.
- Tom wants to tag some contracts, he uses the Tags Registry on Arbitrum to submit several tags. 
- Charles disagrees with a tag and challenges it.
- A dispute is created: John, Joe and Jimmy are likely drawn
- Tom and Charles submit evidence to support their claims.
- The dispute resolves (keep the appeal period short for the demo).
- John, Joe and Jimmy get rewarded or penalized for their voting.
- The tag registry enforces the court decision

#### PNK staking ✅ 
- [x] Smart contracts
- [x] #84 
- [x] #256  
- [ ] #247 (delayed stakes)

#### Dispute creation ✅ 
- [x] Smart contracts
- [x] #84 

#### Dispute appeal ❓ 
⚠️ Arbitrable frontend needs changes.
- [x] Smart contracts
- [x] #84 

#### Juror drawing ✅ 
- [x] Smart contracts
- [x] #84 
- [x] #256 
- [ ] #247
- [ ] #248 "you have been drawn"

#### Evidence submission ✅ 
- [x] Smart contracts
- [x] #84 
- [ ] #259
- [ ] #248 "New evidence submitted for a dispute"
- [x] #254

#### Juror voting ✅ 
- [x] Smart contracts
- [x] #84 
- [x] #260
- [ ] #274
- [ ] #275
- [ ] #247
- [ ] #248 "time to vote"

#### Juror commit/reveal voting ❌
- [x] Smart contracts
- [x] #84 
- #250 
- #247
- #248 "time to commit (or reveal) your vote"

#### Phases automation ✅ 
- [x] Smart contracts
- [x] #84 
- [ ] #247

#### Dispute periods automation ✅ 
- [x] Smart contracts
- [x] #84 
- [ ] #247
- [ ] #248 "dispute has entered phase X"

#### Token and ETH redistribution ✅ 
- [x] Smart contracts
- [x] #84 
- [ ] #263  
- [ ] #264 
- [ ] #247
- [ ] #248 "you have won/lost some PNK and ETH"

#### Ruling execution ✅ 
- [x] Smart contracts
- [x] #84 
- [ ] #247

#### Others
- [x] #283 
- [x] #290 
- [x] #294

---

#### Curate Tag Registry (plan A)  ✅ 
- [x] https://github.com/kleros/tcr/issues/62
- [x] https://github.com/kleros/gtcr-subgraph/issues/16
- [x] https://github.com/kleros/gtcr-injected-uis/issues/6
- [x] https://github.com/kleros/gtcr/issues/255
- [x] https://github.com/kleros/gtcr/issues/256
- [x] https://github.com/kleros/gtcr-action-bot/issues/19

Features:
- Submission of a new tag ✅ 
- Challenge of a pending tag ✅ 
- Execution of the arbitrator's ruling ✅ 
- Appeal ❌

#### Dispute Resolver (plan B) ✅ 
- [x] #96 
- [x] https://github.com/kleros/dispute-resolver/issues/125 

---

### Fast Bridge❓
⚠️ Likely not enough time to bot it, demo it later.
- [x] Smart contracts
- [x] #219 
- #218 

#### Fast Bridge Automation
Either one of these:
- #135 
- Simple Fast Bridge Frontend

#### Features
- Dispute creation from L1
- Ruling execution to L1
