### ISSUE TITLE
Onboarding mini-guides

### ISSUE THREAD

**Issue by jaybuidl** [kleros/kleros-v2#266]
```[tasklist]
### Tasks
- [ ] #267
- [ ] #268
- [ ] #269
- [ ] #270
- [ ] https://github.com/kleros/kleros-v2/issues/1301
- [ ] #271
- [ ] https://github.com/kleros/kleros-v2/issues/1450
- [ ] https://github.com/kleros/kleros-v2/issues/1458
```

**Comment by kemuru** [comment]
fixeed
