### ISSUE TITLE
Curate arbitrable for Kleros v2

### ISSUE THREAD

**Issue by jaybuidl** [kleros/kleros-v2#305]
- [x] https://github.com/kleros/tcr/issues/62
- [x] https://github.com/kleros/gtcr-subgraph/issues/16
- [x] https://github.com/kleros/gtcr-injected-uis/issues/6
- [x] https://github.com/kleros/gtcr/issues/255
- [x] https://github.com/kleros/gtcr/issues/256
- [x] https://github.com/kleros/gtcr-action-bot/issues/19

Blocker for #253

**Comment by jaybuidl** [comment]
### Light Curate Contracts
- LightGeneralizedTCR: [0xbF8d2aA8002c8E606DE16C3f3805335fC143CB21](https://testnet.arbiscan.io/address/0xbF8d2aA8002c8E606DE16C3f3805335fC143CB21)
- LightGeneralizedTCRView: [0xE86f3aA740E47B35CB974dF79897Ca2c8467ac72](https://testnet.arbiscan.io/address/0xE86f3aA740E47B35CB974dF79897Ca2c8467ac72)
- LightBatchWithdraw: [0x2692c903E6bFcc1420b7396AD2841bC199A3Bd9f](https://testnet.arbiscan.io/address/0x2692c903E6bFcc1420b7396AD2841bC199A3Bd9f)
- LightGTCRFactory: [0xBf429eA497b295Ecb26c5dbfF396C90df82F4b44](https://testnet.arbiscan.io/address/0xBf429eA497b295Ecb26c5dbfF396C90df82F4b44)
- List for the Telegram groups: [0x5e49756dda40da16ee0d084ee749da270f926f17](https://testnet.arbiscan.io/address/0x5e49756dda40da16ee0d084ee749da270f926f17) (created by the factory)
- List for the Telegram groups bis: [0x5ad38f241f7c743b7341e732981f65987973adc7](https://testnet.arbiscan.io/address/0x5ad38f241f7c743b7341e732981f65987973adc7) (created by the factory)

### Classic Curate Contracts
- GeneralizedTCR: ??
- GeneralizedTCRView: [0x593D08efEC199890360A4CD5B5b62a97B9317583](https://testnet.arbiscan.io/address/0x593D08efEC199890360A4CD5B5b62a97B9317583)
- BatchWithdraw: [0xb96f168BEF8c3Ce0EDEC0c85556D8F721B79709E](https://testnet.arbiscan.io/address/0xb96f168BEF8c3Ce0EDEC0c85556D8F721B79709E)
- GTCRFactory: [0x65b966068F7cce87526C15D143daDf79476BD0A9](https://testnet.arbiscan.io/address/0x65b966068F7cce87526C15D143daDf79476BD0A9)

### Others
- TransactionBatcher: [0x6396904204e6c430B0e9E6c9EEafD09B7cCC428F](https://testnet.arbiscan.io/address/0x6396904204e6c430B0e9E6c9EEafD09B7cCC428F)
