### ISSUE TITLE
Clean-up post extraction of the Vea code

### ISSUE THREAD

**Issue by jaybuidl** [kleros/kleros-v2#414]
- [x] Removal of the subgraph-fastbridge package
- [x] Removal of the bridge deployment scripts and artifacts
- [x] Removal of the bridge testing code from the test scripts
- [x] Creation of a Vea mock for testing
- [x] #415
