### ISSUE TITLE
Feb 2023 Demo Checklist

### ISSUE THREAD

**Issue by jaybuidl** [kleros/kleros-v2#518]
## UI Cosmetic Fixes
  - [x] kleros/kleros-v2#523
  - [x] kleros/kleros-v2#524
  - [x] kleros/kleros-v2#525
  - [x] kleros/kleros-v2#532
  - [x] kleros/ui-components-library#29
    - [x] Release ui-components-library to NPM and bump version in kleros-v2/web
  - [x] kleros/kleros-v2#533
  - [x] kleros/kleros-v2#529
  - [x] kleros/kleros-v2#530
  - [x] kleros/kleros-v2#531
  - [x] kleros/kleros-v2#534

## Frontend features
  - [x] https://github.com/kleros/kleros-v2/pull/516
  - [x] Estuary migration
    - [x] #549
    - [x] kleros/kleros-v2#538
    - [x] #551
  - [x] kleros/kleros-v2#556

## Vea
- [x] https://github.com/kleros/vea/issues/57
- [x] Re-release the Vea NPM package

## Arbitrable
  - [x] https://github.com/kleros/kleros-v2/pull/511 
  - [x] MetaEvidence must match the one of Curate v1 on Gnosis chain.
  - [x] Arbitrable deployment on Chiado

## Arbitrator
  - [x] kleros/kleros-v2#520
  - [x] kleros/kleros-v2#537
  - Randomizer.ai testing
    - [x] https://github.com/kleros/kleros-v2/pull/519
  - [x] #558
  - [x] kleros/kleros-v2#521

## Legacy Arbitrator on Chiado
- [x] #458 
  - [x] https://github.com/kleros/xdai-kleros-liquid/pull/19
  - [x] kleros/kleros-v2#536
- [x] https://github.com/kleros/kleros-v2/pull/535
- [x] #552
- [x] #553

**Comment by jaybuidl** [comment]
## Post-demo stuffs
  - [ ] kleros/kleros-v2#522
    - Could be fixed after the demo if we focus on the xKlerosLiquid courts only. Requires input from William.
- [ ] Staking rewards: integrate with the claim contract and correct APY.
- [ ] Dashboard: define the metrics formulas.
- [ ] Notifications
- [ ] Settings
- [ ] Help: link to Gitbooks
- [ ] Gitbooks section for the court v2
